### ISSUE TITLE
USER STORY/Task:  Create core Dango site

### ISSUE THREAD

**Issue by DeeMcCart** [Vasileios20/infinity-hub#10]
As  a **devloper** I want to **have a core site** so I can **do wonderful things with Django apps, HTML and CSS (and other stuff?)**

**Acceptance Criteria**:
- Core Django site created
- AllAuth installed?

**Tasks**:
- [x] Task Create repo
- [x] Task Create core Django site with allauth installed
- [x]  Task Create first deployment?
